// Generated by tools/iff-dump/make_uipal_canon.py — do not hand-edit.
// Byte-verbatim UIGraphics.far members (name+len+sha256) + verified anchor colors.
public static readonly R87ResourceCanon[] UIPaletteCanon = new R87ResourceCanon[] {
    new R87ResourceCanon("cpanel\\Backgrounds\\CreateACharBack.BMP", 312210, "03b018df76cbc208b787029bf6bbac66a8d30699d6c0f66ae061a6b7a9999d8c"),
    new R87ResourceCanon("cpanel\\Backgrounds\\PanelBack.bmp", 25122, "b96367fd6cc5f7b6feb6866fea4e469e9d6671cdac743a957185448b714a8aff"),
    new R87ResourceCanon("cpanel\\Buttons\\JobFriendSmiley.bmp", 1554, "e2a995c8c895e51fe7b4896a559f579c796e737cc773fd435df2f1c0b212e4b7"),
    new R87ResourceCanon("cpanel\\Buttons\\Mood.bmp", 5846, "a75482e1930bfd4d5c256134441f32e45f3b45143d0b5116c1b9b7a6d7c74050"),
    new R87ResourceCanon("cpanel\\Catalog\\BuySTDining.bmp", 6408, "188a2f76a6359356f9e3c8b93d9c295797d1571235980a8b678d1285aab990b7"),
};
// (rgbHex, memberIndex) verified at >= 16 px
public static readonly (string rgb, int member)[] UIPaletteAnchors = new (string, int)[] {
    ("000029", 1),
    ("000052", 1),
    ("00004A", 1),
    ("080852", 1),
    ("73739C", 1),
    ("636394", 1),
    ("5A5A8C", 1),
    ("00186B", 0),
    ("00106B", 0),
    ("001063", 0),
    ("72729E", 4),
    ("7474A0", 4),
    ("00FFFF", 3),
    ("00FFFF", 2),
};
