<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <AssemblyName>work_probe</AssemblyName>
    <NoWarn>CS0649</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../FreeSO/TSOClient/tso.files/FSO.Files.csproj" />
  </ItemGroup>
</Project>
