// Round 54 IFF-LITERAL sound-corpus census: generated by tools/iff_objd_audio_census.py over
// game-data/The Sims. Mirrors the ORIGINAL engine mount semantics (TS1Provider.BuildDictionary):
// IFF members mounted per sound extension, keyed by lowercased BASENAME, members excluded when the
// basename contains "globals", LAST-far-wins per basename key - the original game sound lookup is
// basename-keyed. The engine TS1Audio must mount exactly this corpus (no invention/loss).
public static readonly Dictionary<string, int> SoundMountCensus = new Dictionary<string, int>{
    { ".wav", 284 },
    { ".mp3", 0 },
    { ".xa", 17438 },
    { ".utk", 0 },
};
