// Round 57 IFF-LITERAL STR-content census: generated by tools/iff_ctss_census.py over
// game-data/The Sims - IFF CTSS chunks/blocks per member BASENAME, LAST-wins per basename
// (engine mount mirror: duplicate-basename members across packs are IFF-literally shadowed).
// STR.Read mirror: fmt 0/-1/-2 all blocks; fmt -3 only language 0/1 items (LanguageSets[0]).
public const int CtssBlockCensus = 3769;
public const int CtssChunkCensus = 1895;
