import struct, os
from collections import Counter
# iff_resource_census.py - Round 55 IFF-LITERAL resource-census generator. Every IFF member TABLE ROW
# per extension (Path.GetExtension(Filename).ToLowerInvariant() mirror) across all .far packs - mirrors
# the engine FAR1Provider EntriesOfType (no dedup, no basename keying). Engine must mount this exact
# IFF resource census - no invention, no loss.
def far_members(path):
    data = open(path,'rb').read()
    if data[0:8] != b'FAR!byAZ': return []
    man = struct.unpack('<I', data[12:16])[0]
    num = struct.unpack('<I', data[man:man+4])[0]
    out = []; off = man+4
    for i in range(num):
        dlen,dlen2,doff = struct.unpack('<III', data[off:off+12])
        nlen = struct.unpack('<H', data[off+12:off+14])[0]
        nm = data[off+16:off+16+nlen].decode('latin1','replace')
        off += 16+nlen
        if dlen2==dlen and 0<doff<len(data) and dlen<len(data): out.append(nm)
    return out
ROOT = 'game-data/The Sims'
fars = []
for dp, dns, fns in os.walk(ROOT):
    for fn in fns:
        if fn.lower().endswith('.far'): fars.append(os.path.join(dp, fn))
fars.sort()
counts = Counter()
nrows = 0
for fp in fars:
    rows = far_members(fp)
    nrows += len(rows)
    for nm in rows:
        base = nm.replace('\\','/').rsplit('/',1)[-1]
        ext = os.path.splitext(base)[1].lower()
        counts[ext] += 1
print('total far member rows:', nrows)
print('distinct extensions:', len(counts))
for ext, n in sorted(counts.items(), key=lambda kv: -kv[1]):
    print('%8d  %s' % (n, (ext or '(none)')))
lines = []
lines.append('// Round 55 IFF-LITERAL resource census: generated by tools/iff_resource_census.py over')
lines.append('// game-data/The Sims. Every IFF member TABLE ROW per extension (Path.GetExtension mirror)')
lines.append('// across all .far packs; the engine FAR1Provider EntriesOfType must mount exactly this')
lines.append('// IFF resource census - no invention, no loss.')
lines.append('public static readonly Dictionary<string, int> ResourceMountCensus = new Dictionary<string, int>{')
for ext, n in sorted(counts.items()):
    lines.append('    { "%s", %d },' % (ext, n))
lines.append('};')
with open('tools/iff-dump/r55-resource-census.cs','w') as g:
    g.write('\n'.join(lines) + '\n')
print('canon written tools/iff-dump/r55-resource-census.cs')
