#!/usr/bin/env python3
# iff_objd_canon.py - IFF-LITERAL full-corpus buy-catalog canon (Round 46 catalog session).
# Walks EVERY original .far under game-data/The Sims (mirror of the engine's FAR1Provider
# '.*\.far' recursive scan), decodes every .iff member's OBJD chunks IFF-literally (u32 ver +
# u16 field array; Price@16 / FunctionFlags@38 / BuildModeType@67 / Disabled@14 / MasterID@8 /
# SubIndex9 int16 / NumGraphics@2), applies IFF-literally the TS1ObjectProvider catalog
# predicate (mirror of TS1SubProvider BuildDictionary('.iff','globals') + passesCatalogCheck
# + category mapping), and emits the C#-embed canonical dict + counts + checksum.
import struct, collections, math, os

ROOT = 'game-data/The Sims'
FIXTURE20 = ['Easel','ChessTable','Beds','Fridges','Stoves','TVs','ShowerC','TubC','TubM',
             'Toilets','Mirrors','ExerciseMachine','BBQ','Bookcases','Computers','Stereos',
             'Bars','HotTub','Recliners','ChairsLR1Tile']

def s16(v):
    return v - 0x10000 if v >= 0x8000 else v

def passes(ff, bmt, dis, mid, si, ng):
    if not (ff > 0 or bmt > 0): return False
    if dis != 0: return False
    if not (mid != 0 or ng > 0): return False
    if not (mid == 0 or si == -1): return False
    return True

def cat(ff, bmt):
    if ff > 0:
        return int(math.log(ff, 2.0))
    return (bmt + 7)

def num_fields(ver):
    # IFF-literal mirror of FSO OBJD.Read numFields mapping (v138 -> 106; the staged
    # Complete-Collection corpus carries 106 u16 fields for EVERY v138 OBJD - Round 47 fix).
    if ver == 138: return 106
    if ver == 139: return 96
    if ver == 140: return 97
    if ver == 141: return 97
    if ver == 142: return 105
    return 80

def far_members(path):
    data = open(path,'rb').read()
    if data[0:8] != b'FAR!byAZ': return {}
    man = struct.unpack('<I', data[12:16])[0]
    num = struct.unpack('<I', data[man:man+4])[0]
    out = {}
    off = man + 4
    for i in range(num):
        dlen, dlen2, doff = struct.unpack('<III', data[off:off+12])
        nlen = struct.unpack('<H', data[off+12:off+14])[0]
        nm = data[off+16:off+16+nlen].decode('latin1','replace')
        off += 16 + nlen
        if dlen2 == dlen and 0 < doff < len(data) and dlen < len(data):
            out[nm.upper()] = (nm, data[doff:doff+dlen])
    return out

def decode_objds(body, fname):
    out = []
    pos = 64
    while pos + 76 <= len(body):
        ct = body[pos:pos+4].decode('latin1','replace')
        sz = struct.unpack_from('>I', body, pos+4)[0]
        cid = struct.unpack_from('>H', body, pos+8)[0]
        lbl = body[pos+12:pos+76].split(bytes([0]))[0].decode('latin1','replace').strip()
        paysz = sz - 76
        payload = body[pos+76:pos+76+paysz] if paysz > 0 else b''
        if ct == 'OBJD' and len(payload) >= 4 + 68*2:
            ver = struct.unpack_from('<I', payload, 0)[0]
            fld = struct.unpack_from('<%dH' % ((len(payload)-4)//2), payload, 4)
            out.append((cid, lbl, ver, fld, fname))
        pos += 76 + paysz
    return out

fars = []
for dp, dns, fns in os.walk(ROOT):
    for fn in fns:
        if fn.lower().endswith('.far'):
            fars.append(os.path.join(dp, fn))
fars.sort()
print('FAR count:', len(fars))

canon = {}
sortcanon = {}
all_objd = 0
for fp in fars:
    mem = far_members(fp)
    for key, (nm, body) in mem.items():
        if not nm.lower().endswith('.iff'): continue
        if 'globals' in nm.lower(): continue
        for (cid, lbl, ver, fld, _) in decode_objds(body, nm):
            all_objd += 1
            guid = (fld[13] << 16) | fld[12]
            price = fld[16]; ff = fld[38]; bmt = fld[67]; dis = fld[14]
            mid = fld[8]; si = s16(fld[9]); ng = fld[2]
            if passes(ff, bmt, dis, mid, si, ng):
                canon[guid] = (price, cat(ff, bmt), fp, cid, lbl)
                nf = num_fields(ver)
                sortcanon[guid] = (
                    fld[37] & 0xFF,
                    (fld[92] & 0xFF) if (len(fld) > 92 and nf > 92) else 0,
                    (fld[93] & 0xFF) if (len(fld) > 93 and nf > 93) else 0,
                    (fld[95] & 0xFF) if (len(fld) > 95 and nf > 95) else 0,
                    (fld[97] & 0xFF) if (len(fld) > 97 and nf > 95) else 0,
                    (fld[101] & 0xFF) if (len(fld) > 101 and nf > 95) else 0,
                    (fld[102] & 0xFF) if (len(fld) > 102 and nf > 95) else 0)

print('OBJDs total (all .far .iff members):', all_objd)
print('catalog-eligible GUIDs (canon):', len(canon))
pc = collections.Counter(p[0] for p in canon.values())
cksum = sum(guid * p[0] for guid, p in canon.items())
print('checksum sum(guid*price) =', cksum)
print('price histogram top-20:')
for price, c in pc.most_common(20):
    print('  price=%d count=%d' % (price, c))

lines = []
lines.append('// Round 46 catalog IFF-LITERAL canon: generated by tools/iff_objd_canon.py over')
lines.append('// game-data/The Sims (all %d .far, %d OBJDs, %d eligible GUIDs, checksum %d).' % (len(fars), all_objd, len(canon), cksum))
lines.append('private static readonly Dictionary<uint, int[]> CatalogCanon = new Dictionary<uint, int[]>{')
for guid, (price, c, fp, cid, lbl) in sorted(canon.items()):
    lines.append('    { 0x%08x, new int[] { %d, %d } },' % (guid, price, c))
lines.append('};')
lines.append('int CatalogEligible = %d;' % len(canon))
lines.append('long CatalogChecksum = %dL;' % cksum)
with open('tools/iff-dump/r46-catalog-canon.cs', 'w') as g:
    g.write('\n'.join(lines) + '\n')
print('canon C# written to tools/iff-dump/r46-catalog-canon.cs')

sln = []
sln.append('// Round 47 catalog SORT-BYTE IFF-LITERAL canon: generated by tools/iff_objd_canon.py over')
sln.append('// game-data/The Sims (%d eligible GUIDs) - IFF-literal mirror of FSO OBJD.Read version' % len(sortcanon))
sln.append('// gating: RoomSort=(byte)RoomFlags@37, Subs=(byte)FunctionSubsort@92, DT=(byte)DTSubsort@93,')
sln.append('// Vac=(byte)VacationSubsort@95, Comm=(byte)CommunitySubsort@97, ST=(byte)STSubsort@101,')
sln.append('// MT=(byte)MTSubsort@102 (IFF-literal: the v138 corpus carries 106 fields and the Round-47')
sln.append('// engine fix parses them all - canon == served == raw IFF bytes, nothing left unread).')
sln.append('public static readonly Dictionary<uint, int[]> CatalogSorts = new Dictionary<uint, int[]>{')
for guid in sorted(sortcanon):
    r, fs, dt, vac, co, st, mt = sortcanon[guid]
    sln.append('    { 0x%08x, new int[] { %d, %d, %d, %d, %d, %d, %d } },' % (guid, r, fs, dt, vac, co, st, mt))
sln.append('};')
with open('tools/iff-dump/r47-sort-canon.cs', 'w') as g:
    g.write('\n'.join(sln) + '\n')
print('sort-byte canon C# written to tools/iff-dump/r47-sort-canon.cs')

print('CSHARP_FIXTURE_ELIGIBLE:')
for name in FIXTURE20:
    found = None
    for dp, dns, fns in os.walk(ROOT):
        for fn in fns:
            if fn.lower() == (name + '.iff').lower():
                found = os.path.join(dp, fn)
    if not found: continue
    mem = far_members(found)
    for key, (nm, body) in mem.items():
        for (cid, lbl, ver, fld, _) in decode_objds(body, nm):
            guid = (fld[13] << 16) | fld[12]
            price = fld[16]; ff = fld[38]; bmt = fld[67]; dis = fld[14]
            mid = fld[8]; si = s16(fld[9]); ng = fld[2]
            if passes(ff, bmt, dis, mid, si, ng):
                print('  %-14s guid=0x%08x price=%d cat=%d' % (name, guid, price, cat(ff, bmt)))
