#!/usr/bin/env python3
# iff_objd_names.py - IFF-LITERAL buy-catalog NAME canon (Round 48).
# Walks every original .far under game-data/The Sims (mirror of FAR1Provider '.*\.far'), decodes
# every OBJD chunk IFF-literally (u32 ver + u16 field array), applies the TS1ObjectProvider
# passesCatalogCheck predicate, and maps each eligible GUID to its IFF chunk LABEL exactly as the
# engine serves it (IObjectCatalogItem.Name = obj.ChunkLabel; IffFile chunkLabel =
# ASCIIEncoding.ASCII.GetString(64 label bytes).TrimEnd('\0') - tso.files IffFile.cs + IoBuffer.cs;
# bytes >= 0x80 map to '?' as .NET ASCII does - census: 0 of 1114 labels have high bytes).
# IFF-literally pins the buy-mode item NAME surface: served Name == raw label.
import struct, os

ROOT = 'game-data/The Sims'

def s16(v):
    return v - 0x10000 if v >= 0x8000 else v

def label_name(lbl):
    # mirror of IffFile.cs chunkLabel = ReadCString(64).TrimEnd('\0'):
    # ASCII decode, high bytes -> '?', strip trailing NULs.
    s = ''.join(chr(b) if b < 0x80 else '?' for b in lbl)
    return s.rstrip('\0')

def passes(ff, bmt, dis, mid, si, ng):
    if not (ff > 0 or bmt > 0): return False
    if dis != 0: return False
    if not (mid != 0 or ng > 0): return False
    if not (mid == 0 or si == -1): return False
    return True

def far_members(path):
    data = open(path,'rb').read()
    if data[0:8] != b'FAR!byAZ': return {}
    man = struct.unpack('<I', data[12:16])[0]
    num = struct.unpack('<I', data[man:man+4])[0]
    out = {}
    off = man + 4
    for i in range(num):
        dlen, dlen2, doff = struct.unpack('<III', data[off:off+12])
        nlen = struct.unpack('<H', data[off+12:off+14])[0]
        nm = data[off+16:off+16+nlen].decode('latin1','replace')
        off += 16 + nlen
        if dlen2 == dlen and 0 < doff < len(data) and dlen < len(data):
            out[nm.upper()] = (nm, data[doff:doff+dlen])
    return out

def decode_objds(body):
    out = []
    pos = 64
    while pos + 76 <= len(body):
        ct = body[pos:pos+4].decode('latin1','replace')
        sz = struct.unpack_from('>I', body, pos+4)[0]
        cid = struct.unpack_from('>H', body, pos+8)[0]
        lbl = body[pos+12:pos+76]
        paysz = sz - 76
        payload = body[pos+76:pos+76+paysz] if paysz > 0 else b''
        if ct == 'OBJD' and len(payload) >= 4 + 68*2:
            ver = struct.unpack_from('<I', payload, 0)[0]
            fld = struct.unpack_from('<%dH' % ((len(payload)-4)//2), payload, 4)
            out.append((cid, label_name(lbl), fld))
        pos += 76 + paysz
    return out

def esc(n):
    # C# string literal escape for IFF labels (ASCII; defensive escapes).
    out = []
    for ch in n:
        c = ord(ch)
        if ch == '\\': out.append('\\\\')
        elif ch == '"': out.append('\\"')
        elif c < 32 or c == 127:
            out.append('\\u%04x' % c)
        else: out.append(ch)
    return ''.join(out)

fars = []
for dp, dns, fns in os.walk(ROOT):
    for fn in fns:
        if fn.lower().endswith('.far'):
            fars.append(os.path.join(dp, fn))
fars.sort()

names = {}
high = 0
for fp in fars:
    mem = far_members(fp)
    for key, (nm, body) in mem.items():
        if not nm.lower().endswith('.iff'): continue
        if 'globals' in nm.lower(): continue
        for (cid, lbln, fld) in decode_objds(body):
            guid = (fld[13] << 16) | fld[12]
            ff = fld[38]; bmt = fld[67]; dis = fld[14]
            mid = fld[8]; si = s16(fld[9]); ng = fld[2]
            if not passes(ff, bmt, dis, mid, si, ng): continue
            if any(ord(c) > 127 for c in lbln): high += 1
            names[guid] = lbln

print('name canon entries:', len(names))
print('labels with high bytes (>=0x80):', high)
assert len(names) == 1114, 'unexpected eligible %d' % len(names)

lines = []
lines.append('// Round 48 catalog NAME IFF-LITERAL canon: generated by tools/iff_objd_names.py over')
lines.append('// game-data/The Sims (%d eligible GUIDs) - every served buy-catalog item Name must equal' % len(names))
lines.append('// the raw OBJD chunk LABEL exactly as the engine serves it (IObjectCatalogItem.Name =')
lines.append('// obj.ChunkLabel; chunkLabel = ASCII.GetString(64 label bytes).TrimEnd(0), high bytes -> ?, tso.files IffFile.cs).')
lines.append('public static readonly Dictionary<uint, string> CatalogNames = new Dictionary<uint, string>{')
for guid in sorted(names):
    lines.append('    { 0x%08x, "%s" },' % (guid, esc(names[guid])))
lines.append('};')
with open('tools/iff-dump/r48-names-canon.cs', 'w') as g:
    g.write('\n'.join(lines) + '\n')
print('canon C# written to tools/iff-dump/r48-names-canon.cs')
# sanity prints
for g in (0x9fb223ce, 0xfdef7fc2, 0x8fed54c2, 0x00e22e1e):
    print('  0x%08x -> %r' % (g, names.get(g)))
