#!/usr/bin/env python3
# iff_objd_behavior.py - IFF-LITERAL per-fixture FULL-RAW + BEHAVIORAL-ENTRY canon (Round 49).
# The 20 ORIGINAL fixture object IFFs are FAR MEMBERS the engine's content provider mounts by name
# (ts1.Get('<Name>.iff') - mirror of FAR1Provider '.*\\.far' + TS1SubProvider '.iff' dictionary).
# This scanner pulls every '<Name>.iff' member from every original .far exactly as the engine's
# recursive mount would see them, decodes OBJDs IFF-literally (u32 ver + u16 field array), applies
# the TS1ObjectProvider passesCatalogCheck predicate, and emits per-fixture (a) a FULL raw field-array
# checksum over the indices the engine OBJD.RawData exposes (v138=104, v136=78 - IFF-literal mirror
# of the Round-47 fixed read) and (b) per-GUID behavioral entry IDs { BHAV_MainID@3, Animation-TableID@11,
# BHAV_Init@40, BHAV_Place@41, BHAV_UserPickup@42, BHAV_Load@44, BHAV_UserPlace@45 }.
import struct, os
try:
    from pathlib import Path
except Exception:
    pass

ROOT = 'game-data/The Sims'
FIXTURES = ['Easel','ChessTable','Beds','Fridges','Stoves','TVs','ShowerC','TubC','TubM','Toilets','Mirrors','ExerciseMachine','BBQ','Bookcases','Computers','Stereos','Bars','HotTub','Recliners','ChairsLR1Tile']

def s16(v):
    return v - 0x10000 if v >= 0x8000 else v

def passes(ff, bmt, dis, mid, si, ng):
    if not (ff > 0 or bmt > 0): return False
    if dis != 0: return False
    if not (mid != 0 or ng > 0): return False
    if not (mid == 0 or si == -1): return False
    return True

def lim_for(ver):
    if ver == 138: return 104
    return 78

def far_members(path):
    data = open(path,'rb').read()
    if data[0:8] != b'FAR!byAZ': return {}
    man = struct.unpack('<I', data[12:16])[0]
    num = struct.unpack('<I', data[man:man+4])[0]
    out = {}
    off = man + 4
    for i in range(num):
        dlen, dlen2, doff = struct.unpack('<III', data[off:off+12])
        nlen = struct.unpack('<H', data[off+12:off+14])[0]
        nm = data[off+16:off+16+nlen].decode('latin1','replace')
        off += 16 + nlen
        if dlen2 == dlen and 0 < doff < len(data) and dlen < len(data):
            out[nm.upper()] = (nm, data[doff:doff+dlen])
    return out

def decode_objds(body):
    out = []
    pos = 64
    while pos + 76 <= len(body):
        ct = body[pos:pos+4].decode('latin1','replace')
        sz = struct.unpack_from('>I', body, pos+4)[0]
        cid = struct.unpack_from('>H', body, pos+8)[0]
        paysz = sz - 76
        payload = body[pos+76:pos+76+paysz] if paysz > 0 else b''
        if ct == 'OBJD' and len(payload) >= 4 + 68*2:
            ver = struct.unpack_from('<I', payload, 0)[0]
            fld = struct.unpack_from('<%dH' % ((len(payload)-4)//2), payload, 4)
            out.append((cid, ver, fld))
        pos += 76 + paysz
    return out

fars = []
for dp, dns, fns in os.walk(ROOT):
    for fn in fns:
        if fn.lower().endswith('.far'):
            fars.append(os.path.join(dp, fn))
fars.sort()

# collect member name -> list of (far path, body), keyed by basename uppercased
by_member = {}
for fp in fars:
    mem = far_members(fp)
    for key, (nm, body) in mem.items():
        if 'globals' in nm.lower(): continue
        by_member.setdefault(os.path.basename(nm).upper(), []).append((fp, body))

res = {}
ambig = []
for fx in FIXTURES:
    hits = by_member.get((fx + '.iff').upper(), [])
    if not hits:
        print(fx, 'MEMBER NOT FOUND'); continue
    if len(hits) > 1:
        ambig.append((fx, [os.path.basename(h[0]) for h in hits]))
    objs = []
    for (fp, body) in hits:
        for (cid, ver, fld) in decode_objds(body):
            guid = (fld[13] << 16) | fld[12]
            ff = fld[38]; bmt = fld[67]; dis = fld[14]
            mid = fld[8]; si = s16(fld[9]); ng = fld[2]
            if passes(ff, bmt, dis, mid, si, ng):
                objs.append((guid, ver, fld))
    objs.sort(key=lambda x: x[0])
    rawsum = 0
    bh = []
    for (guid, ver, fld) in objs:
        lim = min(lim_for(ver), len(fld))
        for i in range(0, lim):
            rawsum += fld[i] * (i + 1)
        bh.append((guid, [fld[3], fld[11], fld[40], fld[41], fld[42], fld[44], fld[45]]))
    res[fx] = (rawsum, bh)

for fx in FIXTURES:
    if fx in res:
        raw, bh = res[fx]
        print('%s raw=%d objs=%d' % (fx, raw, len(bh)))
        for (g, b) in bh:
            print('   0x%08x main=%d anim=%d init=%d place=%d upick=%d load=%d uplc=%d' % (g, b[0], b[1], b[2], b[3], b[4], b[5], b[6]))
print('ambiguous fixture members:', ambig if ambig else 'none')

lines = []
lines.append('// Round 49 per-fixture FULL-RAW + BEHAVIORAL-ENTRY IFF-LITERAL canon: generated by')
lines.append('// tools/iff_objd_behavior.py over game-data/The Sims (20 ORIGINAL fixture objects; IFF-literal')
lines.append('// mirror of the engine OBJD.RawData surface: v138=104 fields, v136=78 fields).')
lines.append('// FixtureRawChecksum = sum over eligible OBJDs of sum(fld[i]*(i+1)) over the engine-exposed')
lines.append('// indices; FixtureBHAVs = per-GUID behavioral entry ids { BHAV_MainID@3, AnimationTableID@11,')
lines.append('// BHAV_Init@40, BHAV_Place@41, BHAV_UserPickup@42, BHAV_Load@44, BHAV_UserPlace@45 }.')
lines.append('public static readonly Dictionary<string, long> FixtureRawChecksum = new Dictionary<string, long>{')
for fx in FIXTURES:
    if fx in res:
        lines.append('    { "%s.iff", %dL },' % (fx, res[fx][0]))
lines.append('};')
lines.append('public static readonly Dictionary<string, Dictionary<uint, int[]>> FixtureBHAVs = new Dictionary<string, Dictionary<uint, int[]>>{')
for fx in FIXTURES:
    if fx in res:
        inner = ', '.join('{ 0x%08x, new int[] { %d, %d, %d, %d, %d, %d, %d } }' % (g, b[0], b[1], b[2], b[3], b[4], b[5], b[6]) for (g, b) in res[fx][1])
        lines.append('    { "%s.iff", new Dictionary<uint, int[]> { %s } },' % (fx, inner))
lines.append('};')
with open('tools/iff-dump/r49-fixture-canon.cs', 'w') as g:
    g.write('\n'.join(lines) + '\n')
print('canon written tools/iff-dump/r49-fixture-canon.cs')
