#!/usr/bin/env python3
# iff_objd_corpus_bhavs.py - IFF-LITERAL whole-serving-corpus OBJD surface canon (Rounds 50/51).
# For every catalog-eligible OBJD across all original .fars (mirror of FAR1Provider '.*\\.far' +
# TS1ObjectProvider passesCatalogCheck) emits per-GUID:
#   CatalogBHAVs   - VM behavioural entry ids { BHAV_MainID@3, AnimationTableID@11, BHAV_Init@40,
#                     BHAV_Place@41, BHAV_UserPickup@42, BHAV_Load@44, BHAV_UserPlace@45 }
#   CatalogRawChecksum - FULL engine-exposed OBJD.RawData field-array checksum (v138=104 fields,
#                     v136=78 fields: IFF-literal mirror of the Round-47 fixed read; sum fld[i]*(i+1)).
import struct, os

ROOT = 'game-data/The Sims'

def s16(v):
    return v - 0x10000 if v >= 0x8000 else v

def passes(ff, bmt, dis, mid, si, ng):
    if not (ff > 0 or bmt > 0): return False
    if dis != 0: return False
    if not (mid != 0 or ng > 0): return False
    if not (mid == 0 or si == -1): return False
    return True

def lim_for(ver):
    if ver == 138: return 104
    return 78

def far_members(path):
    data = open(path,'rb').read()
    if data[0:8] != b'FAR!byAZ': return {}
    man = struct.unpack('<I', data[12:16])[0]
    num = struct.unpack('<I', data[man:man+4])[0]
    out = {}
    off = man + 4
    for i in range(num):
        dlen, dlen2, doff = struct.unpack('<III', data[off:off+12])
        nlen = struct.unpack('<H', data[off+12:off+14])[0]
        nm = data[off+16:off+16+nlen].decode('latin1','replace')
        off += 16 + nlen
        if dlen2 == dlen and 0 < doff < len(data) and dlen < len(data):
            out[nm.upper()] = (nm, data[doff:doff+dlen])
    return out

def decode_objds(body):
    out = []
    pos = 64
    while pos + 76 <= len(body):
        ct = body[pos:pos+4].decode('latin1','replace')
        sz = struct.unpack_from('>I', body, pos+4)[0]
        cid = struct.unpack_from('>H', body, pos+8)[0]
        paysz = sz - 76
        payload = body[pos+76:pos+76+paysz] if paysz > 0 else b''
        if ct == 'OBJD' and len(payload) >= 4 + 68*2:
            ver = struct.unpack_from('<I', payload, 0)[0]
            fld = struct.unpack_from('<%dH' % ((len(payload)-4)//2), payload, 4)
            out.append((cid, ver, fld))
        pos += 76 + paysz
    return out

fars = []
for dp, dns, fns in os.walk(ROOT):
    for fn in fns:
        if fn.lower().endswith('.far'): fars.append(os.path.join(dp, fn))
fars.sort()

store = {}
for fp in fars:
    mem = far_members(fp)
    for key, (nm, body) in mem.items():
        if not nm.lower().endswith('.iff'): continue
        if 'globals' in nm.lower(): continue
        for (cid, ver, fld) in decode_objds(body):
            guid = (fld[13] << 16) | fld[12]
            ff = fld[38]; bmt = fld[67]; dis = fld[14]
            mid = fld[8]; si = s16(fld[9]); ng = fld[2]
            if passes(ff, bmt, dis, mid, si, ng):
                store[guid] = (ver, fld)

bhavcano = {}
rawcano = {}
for guid, (ver, fld) in store.items():
    bhavcano[guid] = [fld[3], fld[11], fld[40], fld[41], fld[42], fld[44], fld[45]]
    lim = min(lim_for(ver), len(fld))
    rawcano[guid] = sum(fld[i] * (i + 1) for i in range(0, lim))

print('corpus OBJD canon entries:', len(bhavcano))
assert len(bhavcano) == 1114, 'unexpected %d' % len(bhavcano)

lines = []
lines.append('// Round 50/51 whole-serving-corpus OBJD-surface IFF-LITERAL canon: generated by')
lines.append('// tools/iff_objd_corpus_bhavs.py over game-data/The Sims (%d eligible GUIDs).' % len(bhavcano))
lines.append('// CatalogBHAVs: VM behavioural entry ids (BHAV_MainID@3, AnimationTableID@11, BHAV_Init@40,')
lines.append('// BHAV_Place@41, BHAV_UserPickup@42, BHAV_Load@44, BHAV_UserPlace@45). CatalogRawChecksum:')
lines.append('// FULL engine-exposed OBJD.RawData field-array checksum (v138=104, v136=78; IFF-literal')
lines.append('// mirror of the Round-47 fixed read). Every engine-exposed byte of every served buyable')
lines.append('// OBJD equals the original IFF.')
lines.append('public static readonly Dictionary<uint, int[]> CatalogBHAVs = new Dictionary<uint, int[]> {')
for guid in sorted(bhavcano):
    v = bhavcano[guid]
    lines.append('    { 0x%08x, new int[] { %d, %d, %d, %d, %d, %d, %d } },' % (guid, v[0], v[1], v[2], v[3], v[4], v[5], v[6]))
lines.append('};')
lines.append('public static readonly Dictionary<uint, long> CatalogRawChecksum = new Dictionary<uint, long>{')
for guid in sorted(rawcano):
    lines.append('    { 0x%08x, %dL },' % (guid, rawcano[guid]))
lines.append('};')
with open('tools/iff-dump/r50-corpus-bhavs-canon.cs', 'w') as g:
    g.write('\n'.join(lines) + '\n')
for guid in (0x9fb223ce, 0xfdef7fc2):
    print('  0x%08x bhav=%s raw=%d' % (guid, bhavcano.get(guid), rawcano.get(guid)))
print('canon written tools/iff-dump/r50-corpus-bhavs-canon.cs')
