import struct, os
def far_members(path):
    data = open(path,'rb').read()
    if data[0:8] != b'FAR!byAZ': return []
    man = struct.unpack('<I', data[12:16])[0]
    num = struct.unpack('<I', data[man:man+4])[0]
    out = []; off = man+4
    for i in range(num):
        dlen,dlen2,doff = struct.unpack('<III', data[off:off+12])
        nlen = struct.unpack('<H', data[off+12:off+14])[0]
        nm = data[off+16:off+16+nlen].decode('latin1','replace')
        off += 16+nlen
        if dlen2==dlen and 0<doff<len(data) and dlen<len(data): out.append(nm)
    return out
ROOT = 'game-data/The Sims'
CENSUS_EXT = ('.wav', '.mp3', '.xa', '.utk')
fars = []
for dp, dns, fns in os.walk(ROOT):
    for fn in fns:
        if fn.lower().endswith('.far'): fars.append(os.path.join(dp, fn))
fars.sort()
counts = {e: 0 for e in CENSUS_EXT}
keys = {e: set() for e in CENSUS_EXT}
fp_samples = {e: [] for e in CENSUS_EXT}
for fp in fars:
    for nm in far_members(fp):
        # mirror engine TS1Provider.BuildDictionary EXACTLY: key = Path.GetFileName(nm.Replace('\\','/')
        # .ToLowerInvariant()); 'globals' basename excluded; LAST-far-wins per basename key (the ORIGINAL
        # game's SoundListener looks up sounds by basename, so IFF-literalism is basename-keyed).
        key = nm.replace('\\', '/').rsplit('/', 1)[-1].lower()
        if 'globals' in key:
            continue
        low = nm.lower()
        for e in CENSUS_EXT:
            if low.endswith(e):
                keys[e].add(key)
                if len(fp_samples[e]) < 3: fp_samples[e].append(nm)
for e in CENSUS_EXT:
    counts[e] = len(keys[e])
for e in CENSUS_EXT:
    print('%s basename-distinct: %d' % (e, counts[e]))
print('total:', sum(counts.values()))
print('sample .wav full paths:', fp_samples['.wav'])
lines = []
lines.append('// Round 54 IFF-LITERAL sound-corpus census: generated by tools/iff_objd_audio_census.py over')
lines.append('// game-data/The Sims. Mirrors the ORIGINAL engine mount semantics (TS1Provider.BuildDictionary):')
lines.append('// IFF members mounted per sound extension, keyed by lowercased BASENAME, members excluded when the')
lines.append('// basename contains "globals", LAST-far-wins per basename key - the original game sound lookup is')
lines.append('// basename-keyed. The engine TS1Audio must mount exactly this corpus (no invention/loss).')
lines.append('public static readonly Dictionary<string, int> SoundMountCensus = new Dictionary<string, int>{')
for e in CENSUS_EXT:
    lines.append('    { "%s", %d },' % (e, counts[e]))
lines.append('};')
with open('tools/iff-dump/r54-snd-census.cs', 'w') as g:
    g.write('\n'.join(lines) + '\n')
print('canon written tools/iff-dump/r54-snd-census.cs')
