import struct, os
# iff_ctss_census.py - Round 57 STR-content census (basename-keyed LAST-WINS mirror of engine mount:
# TS1Provider BuildDictionary/FAR1Provider EntriesByName keep the LAST far's member per filename; IFF
# members with duplicate basenames across packs are IFF-literally last-wins-deduped, so 4 IFF CTSS
# chunks in earlier packs are IFF-literally shadowed. IFF data, engine-independent; engine STR.Read
# semantics: fmt 0/-1/-2 -> numStrings u16 (all in LanguageSets[0]); fmt -3 -> language byte, only
# lang 0/1 items land in LanguageSets[0].)
def far_members(path):
    data = open(path,'rb').read()
    if data[0:8] != b'FAR!byAZ': return []
    man = struct.unpack('<I', data[12:16])[0]
    num = struct.unpack('<I', data[man:man+4])[0]
    out = []; off = man+4
    for i in range(num):
        dlen,dlen2,doff = struct.unpack('<III', data[off:off+12])
        nlen = struct.unpack('<H', data[off+12:off+14])[0]
        nm = data[off+16:off+16+nlen].decode('latin1','replace')
        off += 16+nlen
        if dlen2==dlen and 0<doff<len(data) and dlen<len(data): out.append(nm)
    return out
ROOT = 'game-data/The Sims'
fars = []
for dp, dns, fns in os.walk(ROOT):
    for fn in fns:
        if fn.lower().endswith('.far'): fars.append(os.path.join(dp, fn))
fars.sort()
def ctss_blocks(payload):
    if len(payload) < 4: return 0
    fmt = struct.unpack_from('<h', payload, 0)[0]
    blocks = 0
    if fmt in (0, -1, -2):
        return struct.unpack_from('<H', payload, 2)[0]
    if fmt == -3:
        n = struct.unpack_from('<H', payload, 2)[0]
        p = 4
        for i in range(n):
            if p >= len(payload): break
            lang = payload[p]; p += 1
            e0 = payload.find(b'\x00', p); e1 = payload.find(b'\x00', e0 + 1) if e0 >= 0 else -1
            if e1 < 0: break
            p = e1 + 1
            if lang == 0 or lang == 1: blocks += 1
        return blocks
    return 0
best = {}  # basename-lower -> (chunks, blocks) last-wins in IFF order
for fp in fars:
    for nm in far_members(fp):
        if not nm.lower().endswith('.iff'): continue
        base = nm.replace('\\', '/').rsplit('/', 1)[-1]
        key = base.lower()
        dat = open(fp.replace(os.sep, os.sep), 'rb').read()
        # re-read member data
        data = open(fp,'rb').read()
        man = struct.unpack('<I', data[12:16])[0]
        num = struct.unpack('<I', data[man:man+4])[0]
        off = man+4
        mdat = None
        for i in range(num):
            dlen,dlen2,doff = struct.unpack('<III', data[off:off+12])
            nlen = struct.unpack('<H', data[off+12:off+14])[0]
            mnm = data[off+16:off+16+nlen].decode('latin1','replace')
            off += 16+nlen
            if mnm == nm:
                mdat = data[doff:doff+dlen]; break
        if mdat is None: continue
        c = 0; b = 0
        pos = 64
        while pos + 76 <= len(mdat):
            ct = mdat[pos:pos+4].decode('latin1','replace')
            sz = struct.unpack_from('>I', mdat, pos+4)[0]
            paysz = sz - 76
            if paysz < 0: break
            if ct == 'CTSS':
                c += 1
                b += ctss_blocks(mdat[pos+76:pos+76+paysz])
            pos += 76 + paysz
        best[key] = (c, b)
chunks = sum(v[0] for v in best.values())
blocks = sum(v[1] for v in best.values())
print('IFF member basenames:', len(best), ' chunks:', chunks, ' blocks:', blocks)
with open('tools/iff-dump/r57-ctss-census.txt','w') as g:
    g.write('basename-keyed CTSS chunks=%d blocks=%d members=%d\n' % (chunks, blocks, len(best)))
lines = ['// Round 57 IFF-LITERAL STR-content census: generated by tools/iff_ctss_census.py over',
         '// game-data/The Sims - IFF CTSS chunks/blocks per member BASENAME, LAST-wins per basename',
         '// (engine mount mirror: duplicate-basename members across packs are IFF-literally shadowed).',
         '// STR.Read mirror: fmt 0/-1/-2 all blocks; fmt -3 only language 0/1 items (LanguageSets[0]).',
         'public const int CtssBlockCensus = %d;' % blocks,
         'public const int CtssChunkCensus = %d;' % chunks]
open('tools/iff-dump/r57-ctss-census.cs','w').write('\n'.join(lines) + '\n')
print('canon written tools/iff-dump/r57-ctss-census.cs')
