#!/usr/bin/env python3
# iff_objd_catalog_order.py - IFF-LITERAL buy-catalog ENUMERATION-ORDER canon (Round 53).
# The served catalog enumerates category-major (IObjectCatalog.All() = ItemsByCategory[0..29] flattened;
# Category = IFF OBJD data: log2(FunctionFlags) or BuildModeType+7), and within each category the
# ORIGINAL IFF FAR-member encounter order (FAR1Provider member-table order; cross-file order = IFF
# path-sorted, the canonical IFF-literalism order). Pin: served enumeration must equal this IFF order.
import struct, os

ROOT = 'game-data/The Sims'

def s16(v):
    return v - 0x10000 if v >= 0x8000 else v

def passes(ff, bmt, dis, mid, si, ng):
    if not (ff > 0 or bmt > 0): return False
    if dis != 0: return False
    if not (mid != 0 or ng > 0): return False
    if not (mid == 0 or si == -1): return False
    return True

def cat(ff, bmt):
    import math
    if ff > 0: return int(math.log(ff, 2))
    return bmt + 7

def far_members(path):
    data = open(path,'rb').read()
    if data[0:8] != b'FAR!byAZ': return {}
    man = struct.unpack('<I', data[12:16])[0]
    num = struct.unpack('<I', data[man:man+4])[0]
    out = []
    off = man + 4
    for i in range(num):
        dlen, dlen2, doff = struct.unpack('<III', data[off:off+12])
        nlen = struct.unpack('<H', data[off+12:off+14])[0]
        nm = data[off+16:off+16+nlen].decode('latin1','replace')
        off += 16 + nlen
        if dlen2 == dlen and 0 < doff < len(data) and dlen < len(data):
            out.append((nm, data[doff:doff+dlen]))
    return out

def decode_objds(body):
    out = []
    pos = 64
    while pos + 76 <= len(body):
        ct = body[pos:pos+4].decode('latin1','replace')
        sz = struct.unpack_from('>I', body, pos+4)[0]
        cid = struct.unpack_from('>H', body, pos+8)[0]
        paysz = sz - 76
        payload = body[pos+76:pos+76+paysz] if paysz > 0 else b''
        if ct == 'OBJD' and len(payload) >= 4 + 68*2:
            ver = struct.unpack_from('<I', payload, 0)[0]
            fld = struct.unpack_from('<%dH' % ((len(payload)-4)//2), payload, 4)
            out.append((cid, fld))
        pos += 76 + paysz
    return out

fars = []
for dp, dns, fns in os.walk(ROOT):
    for fn in fns:
        if fn.lower().endswith('.far'): fars.append(os.path.join(dp, fn))
fars.sort()

items = []  # (category, guid)
for fp in fars:
    members = far_members(fp)
    for (nm, body) in members:
        if not nm.lower().endswith('.iff'): continue
        if 'globals' in nm.lower(): continue
        for (cid, fld) in decode_objds(body):
            guid = (fld[13] << 16) | fld[12]
            ff = fld[38]; bmt = fld[67]; dis = fld[14]
            mid = fld[8]; si = s16(fld[9]); ng = fld[2]
            if passes(ff, bmt, dis, mid, si, ng):
                items.append((cat(ff, bmt), guid))

ids = sorted(set(guid for (c, guid) in items))
print('order entries:', len(items), 'distinct guids:', len(ids))
assert len(ids) == 1114, 'unexpected %d' % len(ids)
# IFF-literalism: duplicate IFF members (same OBJD GUID in >1 far) mount ONCE - first IFF member
# encounter wins - mirroring the engine's 1114 unique serves.
seen = set()
items_u = []
for (c, guid) in items:
    if guid in seen:
        continue
    seen.add(guid)
    items_u.append((c, guid))
assert len(items_u) == 1114, 'unexpected %d' % len(items_u)
items = items_u
# IFF-literalism: served enumeration is CATEGORY-MAJOR (IObjectCatalog.All() = ItemsByCategory[0..29]
# flattened; Category = IFF OBJD log2(FunctionFlags) or BuildModeType+7). Canon = (category asc, IFF
# FAR-member encounter order within category).
items.sort(key=lambda t: (t[0], -1))  # placeholder; real key below by index
items = sorted(items, key=items.index)  # stable original member order
items = sorted(items, key=lambda t: t[0])

lines = []
lines.append('// Round 53 IFF-LITERAL buy-catalog ENUMERATION-ORDER canon: generated by')
lines.append('// tools/iff_objd_catalog_order.py over game-data/The Sims (1114 GUIDs). Served catalog order')
lines.append('// must equal: category-major asc (Category = IFF OBJD log2(FunctionFlags) or BuildModeType+7),')
lines.append('// then ORIGINAL IFF FAR-member encounter order, cross-file IFF path-sorted.')
lines.append('public static readonly uint[] CatalogOrderArray = new uint[] {')
cur = None
buf = []
for (c, guid) in items:
    if c != cur:
        if cur is not None:
            buf.append('    // category %d (%d items)' % (cur, 1))
        cur = c
    buf.append('    0x%08x,' % guid)
lines.append('\n'.join(buf))
lines.append('};')
with open('tools/iff-dump/r53-order-canon.cs', 'w') as g:
    g.write('\n'.join(lines) + '\n')
print('first 8:', ' '.join('0x%08x' % g for (c, g) in items[:8]))
print('canon written tools/iff-dump/r53-order-canon.cs')
