import io
src = open('tools/iff-dump/r47-sort-canon.cs').read()
body = []
for ln in src.splitlines():
    t = ln.strip()
    if t.startswith('{ 0x'):
        body.append(t)
print('generated entries:', len(body))
assert len(body) == 1114, 'unexpected entry count %d' % len(body)

p = 'Client/Simitone/Simitone.Client/AutotestCatalogCanon.cs'
txt = open(p).read()
marker = "        // Round 47 'catalog' SORT-BYTE IFF-LITERAL canon:"
i = txt.index(marker)
j = txt.index('        };', i)
old_len = j + len('        };')
old_block = txt[i:old_len]
old_entries = sum(1 for ln in old_block.splitlines() if ln.strip().startswith('{ 0x'))
print('old embedded entries (to replace):', old_entries)

NL = chr(10)
head = [
    "        // Round 47 'catalog' SORT-BYTE IFF-LITERAL canon: generated by tools/iff_objd_canon.py over"
    , "        // game-data/The Sims (1114 eligible GUIDs) - mirror of FSO OBJD.Read version gating:"
    , "        // RoomSort=(byte)RoomFlags@37, Subs=(byte)FunctionSubsort@92, DT=(byte)DTSubsort@93,"
    , "        // Vac=(byte)VacationSubsort@95, Comm=(byte)CommunitySubsort@97, ST=(byte)STSubsort@101,"
    , "        // MT=(byte)MTSubsort@102 (IFF-literal: the v138 corpus carries 106 fields and the Round-47"
    , "        // engine fix parses them all - canon == served == raw IFF bytes, nothing left unread)."
    , "        public static readonly Dictionary<uint, int[]> CatalogSorts = new Dictionary<uint, int[]>{"
]
ent = ['            ' + e for e in body]
close = ["        };"]
newblock = NL.join(head + ent + close) + NL
out = txt[:i] + newblock + txt[old_len:]
open(p, 'w').write(out)
print('patched OK; embedded entries:', len(body))